apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: brick-breaker

commonLabels:
  app.kubernetes.io/part-of: project-sentinel
  app.kubernetes.io/managed-by: flux

resources:
  - namespace.yaml
  - agent-runtime/
  - web-ui/
  - database/
  - ingress.yaml
  - network-policies.yaml
