apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: brick-breaker-prod

resources:
  - ../../base

images:
  - name: ghcr.io/keithallenjackson/il5-brick-breaker/agent-runtime
    newTag: b8463471f37dc1e915caab668f46b0557296d3b3
  - name: ghcr.io/keithallenjackson/il5-brick-breaker/web-ui
    newTag: b8463471f37dc1e915caab668f46b0557296d3b3

patches:
  # Production: 3 replicas for API, 2 for UI
  - target:
      kind: Deployment
      name: agent-runtime
    patch: |
      - op: replace
        path: /spec/replicas
        value: 3
  - target:
      kind: Deployment
      name: web-ui
    patch: |
      - op: replace
        path: /spec/replicas
        value: 2
  # Higher resource limits for production
  - target:
      kind: Deployment
      name: agent-runtime
    patch: |
      - op: replace
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: "1"
            memory: 512Mi
  - target:
      kind: StatefulSet
      name: postgresql
    patch: |
      - op: replace
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: "1"
            memory: 1Gi
  - target:
      kind: StatefulSet
      name: postgresql
    patch: |
      - op: replace
        path: /spec/volumeClaimTemplates/0/spec/resources/requests/storage
        value: 20Gi
  # Production CORS origins
  - target:
      kind: Deployment
      name: agent-runtime
    patch: |
      - op: replace
        path: /spec/template/spec/containers/0/env/1/value
        value: '["https://brickbreak.keithjackson.dev"]'
