apiVersion: v1
kind: Namespace
metadata:
  name: brick-breaker-dev
  labels:
    app.kubernetes.io/part-of: project-sentinel
---
apiVersion: v1
kind: Namespace
metadata:
  name: brick-breaker-prod
  labels:
    app.kubernetes.io/part-of: project-sentinel
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: v1
kind: Namespace
metadata:
  name: kyverno
